server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称,在c盘的hosts文件提前做好映射，eureka7001.com其实就是localhost
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server监护的地址查询服务和注册服务都需要依赖这个地址，与另一个Eureka Server相互注册，守望着eureka7002.com:7002
      defaultZone: http://eureka7002.com:7002/eureka/
