#表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80
#服务别名---注册zookeeper到注册中心名称

spring:
  application:
    name: cloud-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                  # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 333
  cloud:
    zookeeper:
      #一个zookeeper的机器的IP加端口号
      connect-string: 192.168.19.129:2181